[tool.bandit]

[tool.black]
line-length = 100
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
known_first_party = 'app'
profile = 'black'
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'

[tool.pytest.ini_options]
markers = []
testpaths = ['tests']

[tool.mypy]
python_version = '3.10'
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = ['app_settings', 'invoke', 'pytest_check']
ignore_missing_imports = true
